module.exports = {
  sidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Product Strategy and Validation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'product-strategy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Technical Architecture and Backend Cloud',
      items: [
        {
          type: 'autogenerated',
          dirName: 'technical-architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Monetization and Financial Scaling',
      items: [
        {
          type: 'autogenerated',
          dirName: 'monetization',
        },
      ],
    },
    {
      type: 'category',
      label: 'Design, Accessibility, and UX',
      items: [
        {
          type: 'autogenerated',
          dirName: 'design-future',
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Science and Future Vision',
      items: [
        {
          type: 'autogenerated',
          dirName: 'design-future',
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations and Compliance',
      items: [
        {
          type: 'autogenerated',
          dirName: 'operations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Marketing and Commercial Growth',
      items: [
        {
          type: 'autogenerated',
          dirName: 'marketing',
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP Agents and Protocol',
      items: [
        {
          type: 'autogenerated',
          dirName: 'technical-architecture/MCP',
        },
      ],
    },
  ],
};
